info:
  title: Qubeacart_partner
  version: 1.0.0
openapi: 3.0.0
paths:
  /qubecart/partner/generatecode/:
    post:
      description: '## Generates partner code for regustration'
      operationId: QubecartPartnerGeneratecodePost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"partner_phone\" : \"9999999991\",\n    \"partner_email\"\
                \ : \"jon.doe@mdummb.com\",\n    \"partner_category\" : 1\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: GENERATE PARTNER CODE
  /qubecart/partner/signup/:
    post:
      description: '## Creates a partner using partner code '
      operationId: QubecartPartnerSignupPost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"partner_code\" : \"yQAYtO\",\n    \"addressline1\"\
                \ : \"112/4\",\n    \"addressline2\" : \"Dr, s.c baneerjee road\"\
                ,\n    \"state_id\" : 1,\n    \"country_id\" : 1,\n    \"pin\" : \"\
                700010\",\n    \"city_id\" : 1,\n    \"password\" : \"1234\",\n  \
                \  \"company_name\": \"stationary 001\",\n    \"billing_name\" : \"\
                stationary 001\",\n    \"gst_numbers\" :\"1234qwerty\",\n    \"pan\"\
                \ : \"asdf12345\"\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: PARTNER CREATE
  /qubecart/partner/login/:
    post:
      description: '## Partner login using email/phone as username and password'
      operationId: QubecartPartnerLoginPost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"username\" : \"souravmondal@msqube.com\",\n    \"password\"\
                \ : \"1234\"\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: PARTNER LOGIN
  /qubecart/partner/checkunique/:
    post:
      description: '## Checks whether a partner is unique or not using phone and email'
      operationId: QubecartPartnerCheckuniquePost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"contact_phone\" : \"9999999999\",\n    \"contact_email\"\
                \ : \"jon.Doe@dummy.com\"\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: CHECK UNIQUE PARTNER
  /qubecart/partner/store/create/:
    post:
      description: '## Creates store for partner'
      operationId: QubecartPartnerStoreCreatePost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"qc_partner_id\" : 13,\n    \"addressline1\" : \"21\"\
                ,\n    \"addressline2\" : \"Bekar street\",\n    \"state_id\" : 1,\n\
                \    \"country_id\" : 1,\n    \"pin\" : \"01580012\",\n    \"city_id\"\
                \ : 1,\n    \"store_name\" : \"wonderland\",\n    \"store_category\"\
                \ : 2\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: CREATE STORE
  /qubecart/partner/store/get/:
    post:
      description: '## Returns stores of customer'
      operationId: QubecartPartnerStoreGetPost
      requestBody:
        content:
          '*/*':
            example:
              value: "{\n    \"qc_partner_id\" : 13\n}"
            schema:
              type: string
            x-link-response: []
      responses:
        '200':
          description: ''
      summary: GET STORE
